apiVersion: workload.codeflare.dev/v1beta1
kind: AppWrapper
metadata:
  name: raytest
  namespace: default
spec:
  resources:
    GenericItems:
    - custompodresources:
      - limits:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 0
        replicas: 1
        requests:
          cpu: 2
          memory: 8G
          nvidia.com/gpu: 0
      - limits:
          cpu: 4
          memory: 8G
          nvidia.com/gpu: 0
        replicas: 2
        requests:
          cpu: 4
          memory: 8G
          nvidia.com/gpu: 0
      generictemplate:
        apiVersion: ray.io/v1alpha1
        kind: RayCluster
        metadata:
          labels:
            controller-tools.k8s.io: '1.0'
            workload.codeflare.dev/appwrapper: raytest
          name: raytest
          namespace: default
        spec:
          autoscalerOptions:
            idleTimeoutSeconds: 60
            imagePullPolicy: Always
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 500m
                memory: 512Mi
            upscalingMode: Default
          enableInTreeAutoscaling: false
          headGroupSpec:
            rayStartParams:
              block: 'true'
              dashboard-host: 0.0.0.0
              num-gpus: '0'
            serviceType: ClusterIP
            template:
              spec:
                containers:
                - env:
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: RAY_USE_TLS
                    value: '0'
                  - name: RAY_TLS_SERVER_CERT
                    value: /home/ray/workspace/tls/server.crt
                  - name: RAY_TLS_SERVER_KEY
                    value: /home/ray/workspace/tls/server.key
                  - name: RAY_TLS_CA_CERT
                    value: /home/ray/workspace/tls/ca.crt
                  image: quay.io/project-codeflare/ray:latest-py39-cu118
                  imagePullPolicy: Always
                  lifecycle:
                    preStop:
                      exec:
                        command:
                        - /bin/sh
                        - -c
                        - ray stop
                  name: ray-head
                  ports:
                  - containerPort: 6379
                    name: gcs
                  - containerPort: 8265
                    name: dashboard
                  - containerPort: 10001
                    name: client
                  resources:
                    limits:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 0
                    requests:
                      cpu: 2
                      memory: 8G
                      nvidia.com/gpu: 0
                  volumeMounts:
                  - mountPath: /home/ray/ray_results
                    name: ray-results
                volumes:
                - name: ray-results
                  persistentVolumeClaim:
                    claimName: my-results
                imagePullSecrets: []
          rayVersion: 2.7.0
          workerGroupSpecs:
          - groupName: small-group-raytest
            maxReplicas: 2
            minReplicas: 2
            rayStartParams:
              block: 'true'
              num-gpus: '0'
            replicas: 2
            template:
              metadata:
                annotations:
                  key: value
                labels:
                  key: value
              spec:
                containers:
                - env:
                  - name: MY_POD_IP
                    valueFrom:
                      fieldRef:
                        fieldPath: status.podIP
                  - name: RAY_USE_TLS
                    value: '0'
                  - name: RAY_TLS_SERVER_CERT
                    value: /home/ray/workspace/tls/server.crt
                  - name: RAY_TLS_SERVER_KEY
                    value: /home/ray/workspace/tls/server.key
                  - name: RAY_TLS_CA_CERT
                    value: /home/ray/workspace/tls/ca.crt
                  image: quay.io/project-codeflare/ray:latest-py39-cu118
                  lifecycle:
                    preStop:
                      exec:
                        command:
                        - /bin/sh
                        - -c
                        - ray stop
                  name: machine-learning
                  resources:
                    limits:
                      cpu: 4
                      memory: 8G
                      nvidia.com/gpu: 0
                    requests:
                      cpu: 4
                      memory: 8G
                      nvidia.com/gpu: 0
                  volumeMounts:
                  - mountPath: /home/ray/ray_results
                    name: ray-results
                volumes:
                - name: ray-results
                  persistentVolumeClaim:
                    claimName: my-results
                imagePullSecrets: []
                initContainers:
                - command:
                  - sh
                  - -c
                  - until nslookup $RAY_IP.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
                    do echo waiting for myservice; sleep 2; done
                  image: busybox:1.28
                  name: init-myservice
      replicas: 1
    - generictemplate:
        apiVersion: networking.k8s.io/v1
        kind: Ingress
        metadata:
          name: ray-dashboard-raytest
          namespace: default
        spec:
          rules:
          - host: ray-dashboard-raytest-default.apps.cluster-kv4f8.dynamic.redhatworkshops.io
            http:
              paths:
              - backend:
                  service:
                    name: raytest-head-svc
                    port:
                      number: 8265
                path: /
                pathType: Prefix
      replicas: 1
    Items: []